main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, add_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('register/', register, name='register'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-product-ajax', add_product_ajax, name='add_product_ajax'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
]

tugas1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import uuid

# Create your models here.
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    seller = models.CharField(max_length=255)
    price = models.IntegerField(validators=[MinValueValidator(1)])
    description = models.TextField()
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    class CategoryChoices(models.TextChoices):
        TECHNOLOGY = 'TECH', 'Technology'
        CLOTHES = 'CLOTHES', 'Clothes'
        HOUSE_THINGS = 'HOUSE', 'House Things'
        MISC = 'MISC', 'Miscellaneous'

    category = models.CharField(
        max_length=10,
        choices=CategoryChoices.choices,
        default=CategoryChoices.MISC,
    )
    
    @property
    def is_good_rated(self):
        return self.rating >= 4

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "seller", "description", "price", "rating", "category"]
        
    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_seller(self):
        seller = self.cleaned_data["seller"]
        return strip_tags(seller)
    
    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

main/views.py
from django.shortcuts import render, redirect
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags


# Create your views here.

@login_required(login_url='/login')
def show_main(request):
    
    context = {
        'npm': '2306213836',
        'name': request.user.username,
        'class': 'PBP C',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return redirect('main:show_main')

    context = {
        'form': form,
        'npm': '2306213836',
        'class': 'PBP C'
    }
    return render(request, "create_product.html", context)

def edit_product(request, id):
    # Get product entry berdasarkan id
    product = Product.objects.get(pk = id)

    # Set product entry sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'form': form,
        'npm': '2306213836',
        'class': 'PBP C'
    }
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get product berdasarkan id
    product = Product.objects.get(pk = id)
    # Hapus product
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response

    else:
        form = AuthenticationForm(request)
        # messages.error(request, "Invalid username or password. Please try again.")
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
@require_POST
def add_product_ajax(request):
    name = strip_tags(request.POST.get("name"))
    seller = strip_tags(request.POST.get("seller"))
    price = float(request.POST.get("price"))
    description = strip_tags(request.POST.get("description"))
    rating = int(request.POST.get("rating"))
    category = request.POST.get("category")
    user = request.user

    new_product = Product(
        name=name, 
        seller=seller,
        price=price, 
        description=description,
        rating=rating, 
        category=category,
        user=user,
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/card_product.html
{% load static %}
<div class="relative break-inside-avoid">
    <div class="relative top-5 bg-gray-600 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-indigo-300">
      <div class="flex bg-gray-900 text-gray-200 p-4 rounded-t-lg border-b-2 border-indigo-300">
        <div class="w-1/2 pr-4">
          <h3 class="font-bold text-xl mb-2">{{ product.name }}</h3>
        </div>
        <div class="w-1/2 pr-4 flex flex-col items-end">
          <p class="text-gray-400">{{ product.category }}</p>
          {% if product.category == 'TECH' %}
              <img src="{% static 'image/tech.png' %}" alt="tech" class="w-10 h-10"/>
          {% elif product.category == 'HOUSE' %}
              <img src="{% static 'image/house.png' %}" alt="house" class="w-10 h-10"/> 
          {% elif product.category == 'CLOTHES' %}
              <img src="{% static 'image/clothes.png' %}" alt="clothes" class="w-10 h-10"/> 
          {% elif product.category == 'MISC' %}
              <img src="{% static 'image/misc.png' %}" alt="misc" class="w-10 h-10"/> 
          {% endif %}

        </div>
      </div>
      <div class="p-4">
        <p class="font-semibold text-[#c5c7c7] text-lg mb-2">{{ product.seller }}</p> 
        <p class="text-gray-700 mb-2">
            <span class="bg-[#878787] bg-opacity-20 text-white rounded p-1">{{ product.description }}</span>
        </p>
        <p class="text-gray-700 mb-2"></p>
          <span class="text-white font-bold text-3xl mb-2">Rp. {{product.formatted_price}}</span>
        </p>
        </p>
        <div class="mt-4">
          <p class="text-yellow-200 font-semibold mt-10">Rating</p>
          <div class="relative pt-1">
            <div class="flex items-center">
              {% for i in "12345" %}
                  {% if product.rating >= i|add:0 %}
                      <span class="text-yellow-500 text-xl">&#9733;</span> <!-- Filled Star (★) -->
                  {% else %}
                      <span class="text-gray-300 text-xl">&#9733;</span> <!-- Empty Star (☆) -->
                  {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="absolute bottom-2 -right-[-15px] flex space-x-1">
          <a href="{% url 'main:edit_product' product.pk %}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
              <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
            </svg>
          </a>
          <a href="{% url 'main:delete_product' product.pk %}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
            </svg>
          </a>
        </div>
      </div>
    </div>
</div>

main/templates/create_product.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Register Product</title>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-[#202121]">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-white">Register Product</h1>
  
    <div class="bg-gray-800 p-8 shadow-md rounded-lg form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-white">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-indigo-400 text-white font-semibold px-6 py-3 rounded-lg hover:bg-indigo-700 transition duration-300 ease-in-out w-full">
            Register Product
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>JualJual</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-[#202121] flex flex-col">
  <div class="p-2 mb-6 relative">
    <div class="w-full px-6  absolute top-[44px] left-0 z-20 hidden md:flex">
      <div class="w-1 bg-indigo-700">
      </div>
    </div>
    <div class="h-full w-full py-6  absolute top-0 left-0 z-20 md:hidden flex ">
      <div class="h-full min-w-4 bg-indigo-700 mx-auto">
      </div>
    </div>
  </div>
  <div id="product_cards"></div>
    <div class="flex justify-center mt-20">
      <a href="{% url 'main:create_product' %}" class="bg-[#262945] hover:bg-[#4f5275] text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
          Register Product
      </a>
      <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-indigo-800 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 ml-6 hover:scale-105" onclick="showModal();">
        Register New Product by AJAX
      </button>
    </div>
    <body class="relative">
      <p class="text-white text-right mr-4 absolute bottom-0 right-0">
        Last Login: {{ user.last_login }}
      </p>
    </body>
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-900 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
      <div id="crudModalContent" class="absolute bg-gray-800 rounded-lg shadow-lg w-3/4 sm:w-2/3 md:w-1/2 lg:w-2/5 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out top-20">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b rounded-t">
          <h3 class="text-xl font-semibold text-white">
            Register New Product
          </h3>
          <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="px-6 py-4 space-y-6 form-style">
          <form id="productForm">
            <div class="mb-4">
              <label for="name" class="block text-sm font-medium text-white">Name</label>
              <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-blue-950" placeholder="Enter your product name" required>
            </div>
            <div class="mb-4">
              <label for="seller" class="block text-sm font-medium text-white">Seller</label>
              <input id="seller" name="seller" rows="3" class="mt-1 block w-full resize-none border border-gray-300 rounded-md p-2 hover:border-blue-950" placeholder="Seller name" required></input>
            </div>
            <div class="mb-4">
              <label for="description" class="block text-sm font-medium text-white">Description</label>
              <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-40 resize-none border border-gray-300 rounded-md p-2 hover:border-blue-950" placeholder="Describe your product" required></textarea>
            </div>
            <div class="mb-4">
              <label for="price" class="block text-sm font-medium text-white">Price</label>
              <input type="number" id="price" name="price" min="1" rows="3" class="mt-1 block w-full resize-none border border-gray-300 rounded-md p-2 hover:border-blue-950" placeholder="Product price" required></input>
            </div>
            <div class="mb-4">
              <label for="rating" class="block text-sm font-medium text-white">Rating</label>
              <input type="number" id="rating" name="rating" min="1" max="5" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-blue-950" placeholder="Product Rating" required>
            </div>
            <div class="mb-4">
              <label for="category" class="block text-sm font-medium text-white">Category</label>
              <select id="category" name="category" rows="3" class="mt-1 block w-full resize-none border border-gray-300 rounded-md p-2 hover:border-blue-950" placeholder ="Choose your product category" required>
                <option value="" disabled selected>Choose your product category</option>
                <option value="TECH">Tech</option>
                <option value="HOUSE">House</option>
                <option value="CLOTHES">Clothes</option>
                <option value="MISC">Miscellaneous</option>
              </select>
            </div>
          </form>
        </div>
        <!-- Modal footer -->
        <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
          <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
          <button type="submit" id="submitProduct" form="productForm" class="bg-indigo-700 hover:bg-indigo-900 text-white font-bold py-2 px-4 rounded-lg">Save</button>
        </div>
      </div>
    </div>
</div>

<script>
  function addProduct() {
    fetch("{% url 'main:add_product_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#productForm')),
    })
    .then(response => refreshProducts())

    document.getElementById("productForm").reset(); 
    document.querySelector("[data-modal-toggle='crudModal']").click();
    hideModal();
    return false;
  }
  
  async function getProducts(){
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshProducts() {
    document.getElementById("product_cards").innerHTML = "";
    document.getElementById("product_cards").className = "";
    const products = await getProducts();
    let htmlString = "";
    let classNameString = "";

    if (products.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <img src="{% static 'image/sedih-banget.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
                <p class="text-center text-gray-600 mt-4">Belum ada data produk pada JualJual.</p>
            </div>
        `;
    }
    else {
        classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full"
        
        products.forEach((item) => {
          const name = DOMPurify.sanitize(item.fields.name);
          const seller = DOMPurify.sanitize(item.fields.seller);
          const description = DOMPurify.sanitize(item.fields.description);

          let formattedPrice = parseFloat(item.fields.price).toLocaleString('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 });

          let starRating = '';
          for (let i = 1; i <= 5; i++) {
            if (item.fields.rating >= i) {
              starRating += `<span class="text-yellow-500 text-xl">&#9733;</span>`; // Filled Star
            } else {
              starRating += `<span class="text-gray-300 text-xl">&#9733;</span>`; // Empty Star
            }
          }
          
          const imageSrc = `${item.fields.category === 'TECH' 
            ? "/static/image/tech.png" 
            : item.fields.category === 'HOUSE' 
                ? "/static/image/house.png" 
                : item.fields.category === 'CLOTHES' 
                    ? "/static/image/clothes.png" 
                    : "/static/image/misc.png"}`;
            htmlString += `
              <div class="relative break-inside-avoid">
                  <div class="relative top-5 bg-gray-600 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-indigo-300">
                    <div class="flex bg-gray-900 text-gray-200 p-4 rounded-t-lg border-b-2 border-indigo-300">
                      <div class="w-1/2 pr-4">
                        <h3 class="font-bold text-xl mb-2">${name}</h3>
                      </div>
                      <div class="w-1/2 pr-4 flex flex-col items-end">
                        <p class="text-gray-400">${item.fields.category}</p>
                        <img src="${imageSrc}" alt="${item.fields.category}" class="w-10 h-10"/>
                      </div>
                    </div>
                    <div class="p-4">
                      <p class="font-semibold text-[#c5c7c7] text-lg mb-2">By ${seller}</p> 
                      <p class="text-gray-700 mb-2">
                          <span class="bg-[#878787] bg-opacity-20 text-white rounded p-1">${description}</span>
                      </p>
                      <p class="text-gray-700 mb-2"></p>
                        <span class="text-white font-bold text-3xl mb-2">${formattedPrice}</span>
                      </p>
                      </p>
                      <div class="mt-4">
                        <p class="text-yellow-200 font-semibold mt-10">Rating</p>
                        <div class="relative pt-1">
                          <div class="flex items-center">
                            ${starRating}
                          </div>
                        </div>
                      </div>
                      <div class="absolute bottom-2 -right-[-15px] flex space-x-1">
                        <a href="/edit-product/${item.pk}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                          </svg>
                        </a>
                        <a href="/delete/${item.pk}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                          </svg>
                        </a>
                      </div>
                    </div>
                  </div>
              </div>
            `;
        });
    }
    document.getElementById("product_cards").className = classNameString;
    document.getElementById("product_cards").innerHTML = htmlString;
  }

refreshProducts();

    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    function showModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');
        
        modal.classList.remove('hidden'); 
        setTimeout(() => {
            modalContent.classList.remove('opacity-0', 'scale-95');
            modalContent.classList.add('opacity-100', 'scale-100');
        }, 50); 
    }

    function hideModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modalContent.classList.remove('opacity-100', 'scale-100');
        modalContent.classList.add('opacity-0', 'scale-95');

        setTimeout(() => {
            modal.classList.add('hidden');
        }, 150); 
    }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);
  document.getElementById("productForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addProduct();
  });
</script>
{% endblock content %}

main/templates/navbar.html
<nav class="bg-black shadow-lg fixed top-0 left-0 z-40 w-screen">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <h1 class="text-2xl font-bold text-center text-white">JualJual</h1>
        <div class="hidden md:flex items-left ml-10">
          <button class="text-white text-center mr-10 hover:font-bold">Home</button>
          <button class="text-white text-center mr-10 hover:font-bold">Products</button>
          <button class="text-white text-center mr-10 hover:font-bold">Categories</button>
          <button class="text-white text-center mr-10 hover:font-bold">Cart</button>
        </div>
      </div>
      <div class="hidden md:flex items-center">
        {% if user.is_authenticated %}
          <div class="hidden lg:flex flex-col item.//\ZSs-left mr-5">
            <span class="text-gray-300 text-left">Welcome, {{ user.username }}</span>
            <p class="text-white text-left mr-4">{{ npm }}, {{ class }}</p>
          </div>
          <a href="{% url 'main:logout' %}" class="text-center text-white bg-red-500 hover:text-white hover:bg-red-700 font-bold py-2 px-4 rounded transition duration-300">
            Logout
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mr-2">
            Login
          </a>
          <a href="{% url 'main:register' %}" class="text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Register
          </a>
        {% endif %}
      </div>
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
          <svg class="w-6 h-6 text-white" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
  <!-- Mobile menu -->
  <div class="mobile-menu hidden md:hidden px-4 w-full md:max-w-full">
    <div class="pt-2 pb-3 space-y-1 mx-auto">
      {% if user.is_authenticated %}
        <span class="block text-gray-300 px-3 py-2">Welcome, {{ user.username }}</span>
        <div class="flex flex-col items-center items-start">
          <button class="text-white text-center mb-4 hover:font-bold">Home</button>
          <button class="text-white text-center mb-4 hover:font-bold">Products</button>
          <button class="text-white text-center mb-4 hover:font-bold">Categories</button>
          <button class="text-white text-center mb-4 hover:font-bold">Cart</button>
        </div>
        <a href="{% url 'main:logout' %}" class="block text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Logout
        </a>
      {% else %}
        <a href="{% url 'main:login' %}" class="block text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
          Login
        </a>
        <a href="{% url 'main:register' %}" class="block text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Register
        </a>
      {% endif %}
    </div>
  </div>

  <script>
    // Mobile menu toggle script
    const btn = document.querySelector("button.mobile-menu-button");
    const menu = document.querySelector(".mobile-menu");

    btn.addEventListener("click", () => {
      menu.classList.toggle("hidden");
    });
  </script>
</nav>